
services:
  mysql:
    image: mysql:8.0
    container_name: mysql8
    restart: unless-stopped
    env_file: .env
    environment:
      - ROOT_PASSWD=$MYSQL_ROOT_PASSWORD
    volumes:
      - "./volumes/dbfile:/var/lib/mysql"
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app

  php:
    build:
      context: ./docker/php/
      dockerfile: Dockerfile
    container_name: php8.1-fpm
    depends_on:
      - mysql
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=mysql:3306
    volumes:
      - "./volumes/www-html:/var/www/html"
    networks:
      - app
    
  nginx:
    image: nginx
    depends_on:
      - php
    container_name: nginx-latest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - "./volumes/www-html:/var/www/html"
      - "./volumes/conf.d:/etc/nginx/conf.d"
    networks:
      - app

volumes:
  www-html:
  conf.d:
  dbfile:

networks:
  app:
    driver: bridge